#!/bin/sh

set -e

case "$1" in
    purge)
        userdel didiwiki || true
	rm -f /var/run/didiwiki.pid

	if [ "`readlink /var/lib/didiwiki/styles.css`" = "/etc/didiwiki/styles.css" ]
	then
	    rm /var/lib/didiwiki/styles.css
	fi

    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
